/// Flutter icons NopCart
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NopCart
///      fonts:
///       - asset: fonts/NopCart.ttf
///
///
///
import 'package:flutter/widgets.dart';

class NopCart {
  NopCart._();

  static const _kFontFam = 'NopCart';
  static const String _kFontPkg = null;

  static const IconData ic_cart =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_category =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_search =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_account =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_address =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_shipping =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_payment =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_confirm_order =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //.........school app
  static const IconData account_circle =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData parent =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fee =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fee_inv =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo =
      IconData(0xf022, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fee_edit =
      IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments =
      IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report =
      IconData(0xf343, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // drawer icons

  static const IconData address_book =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vcard =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_1 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manage_account =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language_change =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translate_language =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_inv =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_1 =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData college =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_us =
      IconData(0xf2c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData FAQs =
      IconData(0xf343, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_cog =
      IconData(0xf4fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_graduate =
      IconData(0xf501, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
